### ISSUE TITLE
Migration to torchviz2

### ISSUE THREAD

**Issue by leo-ware** [szagoruyko/pytorchviz#86] opened 2024-09-28 15:45 UTC
As was mentioned in #83, this package is breaking with python 3.12, and it appears to be abandoned by the original maintainer. I've fixed the issue and republished the package as `torchviz2`.

So, just run:
`pip install torchviz2`

And then, this will work:
`import torchviz`

**Comment by johndpope** [comment] 2024-09-30 19:34
thanks again for doing this. when i have time - i'll look at enhancements. shouldn't take long. 
just use chatgpt / claude.

**Comment by szagoruyko** [comment] 2024-12-30 20:51
could not reproduce, closing

**Closed by szagoruyko** 2024-12-30 20:51 UTC
